apiVersion: apps/v1
kind: Deployment
metadata:
  name: mavenapp
  labels:
    app: mavenapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mavenapp
  template:
    metadata:
      labels:
        app: mavenapp
    spec:
      containers:
      - name: mavenapp
        image: tomcat:9.0  # Using the official Tomcat image, modify if a custom image is required
        ports:
        - containerPort: 8080  # Tomcat's default port
        volumeMounts:
        - name: mavenapp
          mountPath: /usr/local/tomcat/webapps  # Tomcat's default directory for WAR files
      volumes:
      - name: mavenapp
        emptyDir: {}  # Placeholder, replace with PersistentVolume if required
