apiVersion: v1
kind: Service
metadata:
  name: mavenapp
  labels:
    app: mavenapp
spec:
  type: NodePort  # Use LoadBalancer if deploying on cloud infrastructure
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: mavenapp
